"""add player_puuids table for alt accounts

Revision ID: 51856e81f4ee
Revises: c67abf08f250
Create Date: 2026-08-28 07:20:43.420886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51856e81f4ee'
down_revision: Union[str, Sequence[str], None] = 'c67abf08f250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_puuids',
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['discord_id'], ['players.discord_id'], ),
    sa.PrimaryKeyConstraint('puuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_puuids')
    # ### end Alembic commands ###
