"""initial schema

Revision ID: 605ed1332162
Revises: 
Create Date: 2026-08-27 04:50:07.657863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605ed1332162'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('map', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reported_by_discord_id', sa.String(), nullable=False),
    sa.Column('team_a_score', sa.Integer(), nullable=False),
    sa.Column('team_b_score', sa.Integer(), nullable=False),
    sa.Column('external_match_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_match_id')
    )
    op.create_table('players',
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('riot_username', sa.String(), nullable=True),
    sa.Column('riot_tag', sa.String(), nullable=True),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('mmr', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('combat_score', sa.Integer(), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('mmr_before', sa.Integer(), nullable=True),
    sa.Column('mmr_after', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discord_id'], ['players.discord_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_participants')
    op.drop_table('players')
    op.drop_table('matches')
    # ### end Alembic commands ###
