"""add puuid and region to players

Revision ID: c67abf08f250
Revises: 605ed1332162
Create Date: 2026-08-28 07:13:26.662514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67abf08f250'
down_revision: Union[str, Sequence[str], None] = '605ed1332162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('puuid', sa.String(), nullable=True))
    op.add_column('players', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'region')
    op.drop_column('players', 'puuid')
    # ### end Alembic commands ###
